### ISSUE TITLE
Add an animated GIF to the README showing use of the application.

### ISSUE THREAD

**Issue by simonprickett** [redis-developer/redis-om-autocomplete-demo#1]
Add an animated GIF to this repository's README showing the application front end being uses for autocomplete lookups.  To be successful with this, you'll need to get the application and Redis up and running locally.

This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/

Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

If you're interested in taking this issue on, please mention @simonprickett and @SuzeShardlow in the comments and ask to be assigned.

**Comment by VedanthB** [comment]
Hi, I would like take this up @simonprickett @SuzeShardlow .

**Comment by SuzeShardlow** [comment]
Hi @VedanthB, I've assigned this to you.  Please check our guidelines and we look forward to seeing your PR in a couple of days.  Have fun!

https://redis.io/community/hacktoberfest/

**Comment by SuzeShardlow** [comment]
Hi @VedanthB, how are you doing with this?  :)

**Comment by VedanthB** [comment]
> Hi @VedanthB, how are you doing with this? :)

Hi @SuzeShardlow , Im facing trouble setting this up locally, I had asked for help on the discord server and was asked to ping @bsbodden for help which I have. Please give me a few more days to submit a PR.

**Comment by SuzeShardlow** [comment]
Thanks for letting me know, @VedanthB!

**Comment by VedanthB** [comment]
Hi @SuzeShardlow, I've tried to set this project up locally but I'm unable to do so. I think you can unassign me so somebody else could take this up and work on it.

**Comment by SuzeShardlow** [comment]
Sorry to hear that, thanks for getting back to me!

**Comment by SuzeShardlow** [comment]
This issue is available and up for grabs. Please tag me and @simonprickett if you would like to work on it :)

**Comment by remote007** [comment]
@SuzeShardlow @simonprickett I would love to work on this issue

**Comment by simonprickett** [comment]
Hi there @remote007 thanks - I've assigned this issue to you and we look forward to receiving your PR in the next couple of days.  Please check out our process here and tag @SuzeShardlow and myself when your PR is ready. https://redis.io/community/hacktoberfest/

**Comment by bsbodden** [comment]
> @SuzeShardlow @simonprickett I would love to work on this issue

@remote007 let me know if you need any help...

**Comment by SuzeShardlow** [comment]
Hi @remote007, how are you getting on with this?  :)

**Comment by mar1boroman** [comment]
@SuzeShardlow @simonprickett - If this is open, would like to work on this

**Comment by SuzeShardlow** [comment]
Hi @mar1boroman, I've assigned this to you. Please check our guidelines and we look forward to seeing your PR in a couple of days.  Have fun!

https://redis.io/community/hacktoberfest/

**Comment by SuzeShardlow** [comment]
> Hi @remote007, how are you getting on with this? :)

@remote007, we haven't heard anything from you, so we have assigned this issue to someone else.

**Comment by mar1boroman** [comment]
@simonprickett @SuzeShardlow - The pull request for this one has been merged. Thanks for the opportunity to participate :) 

P.S.  I missed to reference this issue in the PR, sorry about that

**Comment by SuzeShardlow** [comment]
@mar1boroman thanks for taking part with us!  If you are a member of our Discord server (https://discord.gg/redis), please let us know your handle so we can give you the `Hacktoberfest 2022` role :)

**Comment by mar1boroman** [comment]
@SuzeShardlow - my discord handle is mar1boroman#6656

**Comment by SuzeShardlow** [comment]
Thanks @mar1boroman!  I've given you the role :)
